apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
      metadata:
        labels:
          app: my-app
      spec:
        containers:
          - name: my-app
            image: nobahar/my-app:v1
            ports:
              - containerPort: 3000
